on:
  push:
  pull_request:
#  schedule:
#    - cron: '9 * * * *'
  workflow_dispatch:

env:
    MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

secrets: inherit

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  generate:
    uses: osdc-code-maven/osdc-2023-01-public/.github/workflows/ci.yml@main
